[tool.poetry]
name = "urban-univer"
version = "0.1.0"
description = ""
authors = ["Alexandr_Tikhonov <tihas75@mail.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
example1 = "^1.0.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
