import tkinter as tk

window = tk.Tk()
window.title('Калькулятор')
window.geometry("350x350")
window.resizable(False, False)
button_add = tk.Button(window, text="+", width=2, height=2)
button_add.place(x=80, y=200)
button_sub = tk.Button(window, text="-", width=2, height=2)
button_sub.place(x=130, y=200)
button_mul = tk.Button(window, text="*", width=2, height=2)
button_mul.place(x=180, y=200)
button_div = tk.Button(window, text="/", width=2, height=2)
button_div.place(x=230, y=200)
number1_entry = tk.Entry(window, width=20)
number1_entry.place(x=90, y=75)
number2_entry = tk.Entry(window, width=20)
number2_entry.place(x=90, y=150)
answer_entry = tk.Entry(window, width=20)
answer_entry.place(x=90, y=300)
number1 = tk.Label(window, text="Введите первое число:")
number1.place(x=90, y=50)
number2 = tk.Label(window, text="Введите второе число:")
number2.place(x=90, y=130)
answer = tk.Label(window, text="Ответ:")
answer.place(x=90, y=275)
window.mainloop()
